apiVersion: v2
appVersion: "1.0.25"
description: NVIDIA Nemotron-Labs-Diffusion 14B — tri-mode (AR + Diffusion + self-spec) on llama.cpp via spiritbuun fork
name: llamacppnemotrondiffusion14b1
type: application
version: 1.0.25
