apiVersion: v2
appVersion: "2.0.39"
description: Qwen3.6 35B-A3B MTP+Vision — GGUF Q3_K_XL, turbo4 KV, MTP n=5, mmproj-gpu-swap on Olares One
name: llamacppqwen36a3bone
type: application
version: 2.0.39
