workloads:
  sndrdiffusiongemma26bone:
    replicaCount: 1
  sndrdiffusiongemma26bonecli:
    replicaCount: 1
olaresEnv:
  HF_TOKEN: ''
  HF_ENDPOINT: ''
  UV_INDEX_URL: ''
  PIP_INDEX_URL: ''
  LLM_CONTEXT_WINDOW: ''
  LLM_MAX_OUTPUT_TOKENS: ''
  LLM_API_KEY: ''
