apiVersion: v2
appVersion: "1.0.13"
description: Qwen3.6 35B-A3B + MTP + Vision — 243 t/s @ FULL 262K context with vision on Olares One (mmproj-gpu-swap unlocks vision on champion)
name: llamacppqwable35bone
type: application
version: 1.0.13
