workloads:
  vllmqwen3635bnvfp4fone:
    replicaCount: 1
  vllmqwen3635bnvfp4fonecli:
    replicaCount: 1
olaresEnv:
  HF_TOKEN: ""
  HF_ENDPOINT: ""
  GITHUB_TOKEN: ""
  GHCR_USER: ""
  LLM_CONTEXT_WINDOW: ""
  LLM_MAX_OUTPUT_TOKENS: ""
  LLM_API_KEY: ""
