userspace:
  appData: ''
  appCache: ''
  userData: ''
  appCommon: ''
workloads:
  llamacppornith35bone:
    replicaCount: 1
  llamacppornith35bonecli:
    replicaCount: 1
olaresEnv:
  GITHUB_TOKEN: ''
  GHCR_USER: ''
  LLM_CONTEXT_WINDOW: ''
  LLM_MAX_OUTPUT_TOKENS: ''
  LLM_API_KEY: ''
  HF_TOKEN: ''
  HF_ENDPOINT: ''
