admin: ''
bfl:
  username: ''
userspace:
  appData: ''
  appCache: ''
  userData: ''
  appCommon: ''
olaresEnv:
  HF_TOKEN: ''
  HF_ENDPOINT: ''
  GITHUB_TOKEN: ''
  GHCR_USER: ''
workloads:
  llamacppqwen3635ba3btq34sone:
    replicaCount: 1
  llamacppqwen3635ba3btq34soncli:
    replicaCount: 1
