admin: ''
bfl:
  username: ''
userspace:
  appData: ''
  appCache: ''
  userData: ''
  appCommon: ''
olaresEnv:
  HF_TOKEN: ''
  HF_ENDPOINT: ''
  GITHUB_TOKEN: ''
  GHCR_USER: ''
  LLM_CONTEXT_WINDOW: ''
  LLM_MAX_OUTPUT_TOKENS: ''
  LLM_API_KEY: ''
  ENABLE_CPU_MOE: '1'
  N_CPU_MOE: ''
  N_GPU_LAYERS: ''
  LAGUNA_QUANT: 'q4_k_m'
  ENABLE_DFLASH: ''
  ENABLE_NO_MMAP: ''
  OVERRIDE_TENSORS: ''
workloads:
  llamacpplagunas21one:
    replicaCount: 1
  llamacpplagunas21onecli:
    replicaCount: 1
