admin: ''
bfl:
  username: ''
userspace:
  appData: ''
  appCache: ''
  userData: ''
olaresEnv:
  HF_TOKEN: ''
  HF_ENDPOINT: ''
  GITHUB_TOKEN: ''
  GHCR_USER: ''
  SGLANG_MODEL_PATH: 'krea/Krea-2-Turbo'
workloads:
  sglangkrea2turboone:
    replicaCount: 1
  sglangkrea2turboonecli:
    replicaCount: 1
