admin: ''
bfl:
  username: ''
userspace:
  appData: ''
  appCache: ''
  userData: ''
olaresEnv:
  GITHUB_TOKEN: ''
  GHCR_USER: ''
  HF_TOKEN: ''
  HF_ENDPOINT: ''
workloads:
  qwen3ttstone:
    replicaCount: 1
  qwen3ttstonecli:
    replicaCount: 1
