admin: ''
bfl:
  username: ''
userspace:
  appData: ''
  appCache: ''
  userData: ''
olaresEnv:
  HF_TOKEN: ''
  HF_ENDPOINT: ''
  GITHUB_TOKEN: ''
  GHCR_USER: ''
workloads:
  sglangernieimageone:
    replicaCount: 1
  sglangernieimageonecli:
    replicaCount: 1
